{{- if and .Values.ingress.enabled (eq .Values.ingress.type "istio") }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "poseiden.fullname" . }}
  labels:
    {{- include "poseiden.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ingress.host | quote }}
  gateways:
    - {{ .Values.ingress.istio.gateway }}
  http:
    - route:
        - destination:
            host: {{ include "poseiden.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
