{{- if and (eq .Values.auth.provider "keycloak") .Values.auth.keycloak.bundled.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poseidon.keycloak.fullname" . }}
  labels:
    {{- include "poseidon.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  selector:
    {{- include "poseidon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}
